apiVersion: v1
kind: Secret
metadata:
  name: q-immune-mesh-secrets
  namespace: default
type: Opaque
data:
  jwt-secret-key: bWktZmlybWEtc2VjcmV0YS1qd3QtMjAyNg==
  # 🧠 COMPORTAMIENTO AJUSTADO: Elevamos el umbral a 0.99 (Texto plano: 0.99 -> Base64: MC45OQ==)
  ai-umbral-anomalia: MC45OQ==
  ai-weight-payload: MC4wNQ==
  ai-weight-burst: MC4xMg==
  ai-weight-entropy: MC4xNQ==
  ai-bias: LTIuNQ==
  pqc-active-engine: S1lCRVI=
  pqc-kyber-variant: S3liZXI3Njg=
  pqc-dilithium-variant: RElMSVRISVVNMw==
