apiVersion: v1
kind: Secret
metadata:
  name: llaves-credenciales-cuanticas
  namespace: default
type: Opaque
data:
  # La clave ultra-secreta para firmar los JWT (Texto: mi-llave-secreta-jwt-2026)
  jwt-secret-key: bWktbGxhdmUtc2VjcmV0YS1qd3QtMjAyNg==
  # 🔐 NUEVO: Contraseña de producción oculta de forma declarativa
  auth-password: cGFzc3dvcmQxMjM=
