apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-red-cuantica-privada
  namespace: metallb-system
spec:
  # Rango virtual exclusivo aislado de tu Wi-Fi y de la IP de tu Mac
  addresses:
  - 172.20.0.50-172.20.0.60
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: anuncio-red-local
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool-red-cuantica-privada
