user root;
worker_processes 1;
pid /tmp/nginx.pid;
events { worker_connections 1024; }
http {
    default_type application/json;
    sendfile on;
    keepalive_timeout 65;
    client_body_temp_path /tmp/client_body;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    server {
        listen 9080;
        server_name localhost;

        location / {
            proxy_pass http://q-immune-mesh-service:9080\;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
